{% set python_min = "3.11" %}
{% set version = "0.2.1" %}

package:
  name: convolinear
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/c/convolinear/convolinear-{{ version }}.tar.gz
  sha256: 063df99298f95f362ac766bfcfc36511ad4f9253c61380e9592a029c3972770f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling >=1.26
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.23.2
    - scipy >=1.9.2

test:
  imports:
    - convolinear
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/sahmed0/convolinear
  summary: Fluent signal processing for Python, one line at a time.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sahmed0
